### PR TITLE
Modify Samsung Internet info

### PR DESCRIPTION
**Pull request by mkeblx**
Basic info.

### CODE REVIEW

**Comment by cvan** [comment]
thanks for these changes. if you want to address these, I can then merge. otherwise, I can do them quickly too. just lmk.

**Comment by mkeblx** [comment]
'address these' referring to what?

**Comment by cvan** [comment]
> 'address these' referring to what?

my comments above; sorry I guess my review didn't get sent

**Comment by cvan** [comment]
made some updates. all looks good. thanks, @mkeblx 👍

**Pull request merged**
