### PR TITLE
Proposed homepage design

### PR DESCRIPTION
**Pull request by darkwing**
So this is a very crude design mockup I put together this morning for the site.  Of course it needs loads of cleaning up but it's at the point where you can get the gist of what it should look like.  @cvan @caseyyee Let's chat about this on Slack.

This is a new design which doesn't use any of the current styles or structure (serve via `python -m SimpleHTTPServer` and hit 0.0.0.0:8000).  We'll use better fonts than the defaults, I simply used `Arial` to note where a different san-serif font would be used.

### CODE REVIEW

**Comment by caseyyee** [comment]
Hey @darkwing thanks for this.  Yes, i think having some kind of blog articles on front page is a good.  

I see 3 different types of personas visiting the site:

Persona 1
New to WebVR
* Knows about VR
* May already have a VR headset
* Wants to understand what WebVR is about

Persona 2
Enthusiast
* May be a consumer of VR experiences.
* Wants to know what’s new in the world of WebVR

Persona 3
Content creator
* Has and uses VR headsets
* Looking for tips, tricks and workflows
* Want to be inspired
* Follows latest trends in frameworks and librariers, 
follows browser development closely.

**Comment by darkwing** [comment]
Per your use cases:

P1: Will be excited by the nav because it encompasses each step of getting into WebVR/VR, plus the masthead demo will be exciting for them.

P2:  They’ll like the masthead demos, the blog posts, and the Showcase

P3:  Showcase area, blog posts will excite them

**Comment by cvan** [comment]
really awesome work, man - I'm digging the more article-focused presentation. great start!

**Comment by cvan** [comment]
for folks who want to try this branch out live without pulling: https://rawgit.com/darkwing/webvrrocks/design/homepage.html

**Comment by cvan** [comment]
thanks, @darkwing. per our hack session with @caseyyee at our Mozilla Hawaii all-hands event, we've got a new homepage and layout - based on everyone's feedback 👍 great work on this and helpng out. thanks!

**Pull request closed without merging**
