### PR TITLE
create headset page for "Samsung Gear VR" (fixes #277)

### LINKED ISSUE #277: Create headset page for Samsung Gear VR
Create page for https://webvr.rocks/samsung_gear_vr (à la https://webvr.rocks/htc_vive). Along with useful links, FAQ, debugging info, etc., it should point to the supported browsers: Oculus Browser, Samsung Internet Browser, and Chrome for Android.

### PR DESCRIPTION
**Pull request by cvan**
I've created a headset page for the Gear VR hardware with helpful FAQ and links to the supported browsers + phones.

The page will live at **https://webvr.rocks/samsung_gear_vr**

<hr>

r? @poshaughnessy @AdaRoseCannon @mkeblx @diekus @caseyyee

<hr>

There are _browser_ pages:

- https://webvr.rocks/samsung_internet
- https://webvr.rocks/oculus_browser

But there haven't been separate _headset_ pages, except the Vive one (which still needs more content):

- https://webvr.rocks/htc_vive

Here's an initial version of headset page I've made for Gear VR:

screenshot-2017-11-10 webvr rocks

(BTW, https://webvr.rocks/gearvr, and a bunch of various redirects are in place.)

FYI: I will be making pages for the rest of the headsets. And I still have lots of more info to add for Gear VR (and its browsers): #275, #276, #245, #242, #272, and a few more.

Thanks for your feedback, everyone!

### CODE REVIEW

**Comment by diekus** [comment]
nice! how can I assist you here?

**Comment by cvan** [comment]
@diekus are there any common FAQ or Troubleshooting issues you see folks encounter with getting their Samsung Gear VR set up (for WebVR and just onboarding in general)? that's mostly what I'm curious about: **common questions and tips**

**Comment by vincentfretin** [comment]
@cvan In the sentence below the title you wrote "with positional tracking". GearVR and DayDream doesn't have positional tracking.
For Samsung Internet, you need to install it yourself from Oculus Store, it is not installed by default, isn't it?
For Samsung Internet, there is now a flag WebVR you need to toggle from the Labs menu
https://github.com/SamsungInternet/support/issues/19

I didn't know GearVR supported Chrome for Android. Are you sure? How do you use it? AFAICT the only browsers you can open with the headset on is Oculus browser and Samsung Internet.

**Comment by machenmusik** [comment]
> I didn't know GearVR supported Chrome for Android. Are you sure? How do you use it? AFAICT the only browsers you can open with the headset on is Oculus browser and Samsung Internet.

I'm not sure whether what is meant here is how to use Chrome for Android in Daydream/Cardboard mode using a Gear VR HMD e.g. on Galaxy S8, which IIRC requires quite a few steps including disabling Gear VR Service and installing a Gear VR profile for Daydream/Cardboard, or something else...

**Comment by vincentfretin** [comment]
@machenmusik Ok yes, so it's not for the end user, this is what I meant here. You can indeed open in stereoscopic mode in chrome for android, but when you then insert the phone in the headset, it opens Oculus lobby. If you know how to disable the launch of Oculus lobby when you insert the phone, I'm interested.

**Comment by cvan** [comment]
> @cvan In the sentence below the title you wrote "with positional tracking". GearVR and DayDream doesn't have positional tracking.

Good catch! Yeah, that was just a typo. I meant tracking only orientation. What do we even call that? Heh, "non-positional VR"? Whatever the term is, I'd love to add it to the eventual Glossary (see issue #65).

> For Samsung Internet, you need to install it yourself from Oculus Store, it is not installed by default, isn't it?

Yes, I think you still have to install it from the Oculus Store/Lobby. per @poshaughnessy's latest updates #224, I think this is correct: https://webvr.rocks/samsung_internet#setup

> For Samsung Internet, there is now a flag WebVR you need to toggle from the Labs menu
https://github.com/SamsungInternet/support/issues/19

Yes, that's correct: https://webvr.rocks/samsung_internet#setup

I'll likely in a follow-up PR, include (or just link to) FAQ from the FAQ on the browser pages for Samsung Internet and Oculus Browser.

> I didn't know GearVR supported Chrome for Android. Are you sure? How do you use it? AFAICT the only browsers you can open with the headset on is Oculus browser and Samsung Internet.

It doesn't – that was my mistake. Thanks for the good catch!

**Comment by cvan** [comment]
> @machenmusik Ok yes, so it's not for the end user, this is what I meant here. You can indeed open in stereoscopic mode in chrome for android, but when you then insert the phone in the headset, it opens Oculus lobby. If you know how to disable the launch of Oculus lobby when you insert the phone, I'm interested.

Yes, I'm also curious if this is possible. @AdaRoseCannon, @DigiTec – do you know if this is possible?

**Comment by cvan** [comment]
updated per feedback from @vincentfretin, et. al. many thanks, everyone!

screenshot-2017-11-14 webvr rocks 1

**Comment by cvan** [comment]
thanks, everyone! much appreciated 👍

**Pull request merged**
