### PR TITLE
add initial Directory (fixes #30)

### LINKED ISSUE #30: Add Directory stub
Port Airtable -> Google Sheets tables -> enable anonymous edits

### PR DESCRIPTION
**Pull request by cvan**
I got this both working with real-time and offline fallback, populated from https://docs.google.com/spreadsheets/d/1K8HArN12v_XQqv8NiNcFNmRW0bGv4Zkn7XAJlY3vth0/edit.

I'm now getting some bug that I can't figure out right now. Hopefully, I can spot and fix it easily when I take a look next.

### CODE REVIEW

**Comment by cvan** [comment]
@caseyyee: screenshots:

screen shot 2016-11-16 at 23 08 13-fullpage

<hr>

screen shot 2016-11-16 at 23 07 44-fullpage

**Comment by cvan** [comment]
temporarily disabled real-time functionality, but it'll be easy to add back in (filed #86)

**Comment by cvan** [comment]
merging! :party:

**Comment by caseyyee** [comment]
awesome!   great start 💯

**Pull request merged**
