### PR TITLE
Win mixed reality master

### PR DESCRIPTION
**Pull request by leweaver**
This updates the color of the Windows logo, as well as alter the wording to Windows Mixed Reality headsets.

### CODE REVIEW

**Comment by caseyyee** [comment]
thanks @leweaver!   Can you rebase the conflict?   Everything else should work with the other changes made today too.

**Comment by leweaver** [comment]
Ah thanks!

**Comment by leweaver** [comment]
Is it possible something weird happened in the merge or deploy? The icon for the WMR devices doesn't seem to be appearing on the index page

**Comment by caseyyee** [comment]
Yeah, I'm just looking into it now.   Strange since it does work with my local server here.

**Comment by caseyyee** [comment]
@leweaver it seems to be working for me now.   May have just been some cache issue.

**Comment by cvan** [comment]
The pages are cached by CloudFlare for 1 hour. If a user comes back after the time at which an update was made, the user will see the new changes. Otherwise, hard-refresh immediately after a deploy, and you can see the changes.

Thanks for the updates, @leweaver and @caseyyee! 👍

**Pull request merged**
